"""Meta endpoints: /v1/status, /v1/usage, /v1/privacy/my-data, /v1/capabilities.

Mounted into the /v1 aggregator (see app/api/main.py) so the router itself
carries no prefix — paths here are relative.
"""

from typing import Annotated

from auth import AuthCtx, require_auth
from config import (
    COST_AUDIT,
    COST_SCAN,
    COST_TECH_CVE_AUDIT,
    COST_THREAT_REPORT,
    FREE_HOURLY_LIMIT,
    MCP_TOOL_COUNT,
    PRO_HOURLY_LIMIT,
    UPGRADE_URL,
    VERSION,
)
from db import get_sync_status
from fastapi import APIRouter, Depends, HTTPException, Response

router = APIRouter(tags=["Meta"])


@router.get("/status", operation_id="api_status")
def api_status(response: Response):
    """API health check and data freshness."""
    response.headers["Cache-Control"] = "public, max-age=60"
    sync = get_sync_status()
    return {
        "status": "ok",
        "version": VERSION,
        "data_sources": {source: {"status": info.get("status")} for source, info in sync.items()},
    }


@router.get("/usage", operation_id="api_usage")
def api_usage(auth: Annotated[AuthCtx, Depends(require_auth("/v1/usage"))]):
    """Usage statistics for API key holders."""
    from db import get_key_usage_stats

    if auth.tier != "pro" or not auth.key_hash:
        raise HTTPException(status_code=401, detail="API key required. Pass Authorization: Bearer cc_xxx")

    stats = get_key_usage_stats(auth.key_hash)
    stats["hourly_limit"] = PRO_HOURLY_LIMIT
    stats["hourly_remaining"] = max(0, PRO_HOURLY_LIMIT - stats["last_1h"])
    return stats


@router.get("/privacy/my-data", operation_id="privacy_my_data")
def privacy_my_data(auth: Annotated[AuthCtx, Depends(require_auth("/v1/privacy/my-data"))]):
    """Return everything this API has stored about you. GDPR-style transparency.

    Shows the hashed IP, Pro key record (if any), and last-24h endpoint usage.
    The raw domains, IPs, CVEs, hashes, or code you submitted are NEVER stored —
    path parameters are stripped before any DB write (see db.normalize_endpoint).
    """
    from db import get_privacy_data

    data = get_privacy_data(auth.client_ip, auth.key_hash)

    tier = auth.tier
    limit = PRO_HOURLY_LIMIT if tier == "pro" else FREE_HOURLY_LIMIT
    remaining = auth.ratelimit_remaining

    return {
        "tier": tier,
        "rate_limit": {
            "hourly_limit": limit,
            "remaining_in_window": remaining,
            "window_seconds": 3600,
        },
        **data,
        "not_stored": [
            "Your raw IP address. Only a salted HMAC hash is stored, used for anonymized analytics.",
            "The domain names, IP addresses, CVE IDs, file hashes, emails, phone numbers, usernames, or source code you submit. Path parameters are stripped before logging — see db.normalize_endpoint at https://github.com/UPinar/contrastapi/blob/main/app/db.py",
            "Response contents. Domain and IP lookups use a 1-hour performance cache keyed by the queried target (not by you); everything else is processed in real time.",
            "Your name, email, phone, or any personal identifier. No signup, no accounts.",
            "Tracking cookies, third-party analytics, or fingerprinting data.",
        ],
        "source_code": {
            "hashing": "https://github.com/UPinar/contrastapi/blob/main/app/db.py (hash_client_ip)",
            "endpoint_normalization": "https://github.com/UPinar/contrastapi/blob/main/app/db.py (normalize_endpoint)",
            "this_endpoint": "https://github.com/UPinar/contrastapi/blob/main/app/main.py (privacy_my_data)",
        },
        "privacy_policy": "https://api.contrastcyber.com/privacy",
        "contact": "contact@contrastcyber.com",
    }


@router.get("/capabilities", operation_id="api_capabilities")
def api_capabilities():
    """Machine-readable catalog of all MCP tools and REST endpoints."""
    return {
        "schema_version": "1.0",
        "api_version": VERSION,
        "base_url": "https://api.contrastcyber.com",
        "total_tools": MCP_TOOL_COUNT,
        "verdict_metadata": True,
        "auth": {
            "type": "none_required",
            "free_tier": {"requests_per_hour": 100},
            "pro_tier": {"requests_per_hour": 1000, "header": "Authorization: Bearer cc_xxx or X-API-Key: cc_xxx"},
        },
        "rate_limit_headers": [
            "X-RateLimit-Limit",
            "X-RateLimit-Remaining",
            "X-RateLimit-Reset",
            "X-RateLimit-Cost",
            "X-RateLimit-Tier",
        ],
        "upgrade_signal": {
            "header": "X-Upgrade-URL",
            "emitted_when": "Only on HTTP 429 responses for free-tier clients",
            "value": UPGRADE_URL,
        },
        "blast_radius_legend": {
            "zero": "Local DB or pure computation. No outbound network to target.",
            "low": "Third-party API lookup or passive DNS/WHOIS/CT. Does not contact target host.",
            "high": "Actively contacts target host (live HTTP, TLS handshake, DNS brute force).",
        },
        "categories": {
            "cve": {
                "description": "CVE intelligence, EPSS scores, CISA KEV, exploit search",
                "tools": [
                    {
                        "name": "cve_lookup",
                        "method": "GET",
                        "path": "/v1/cve/{cve_id}",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Full CVE details with EPSS score, KEV status, CVSS breakdown",
                        "response_keys": [
                            "cve_id",
                            "summary",
                            "severity",
                            "cvss_v3",
                            "epss",
                            "kev",
                            "affected_products",
                        ],
                    },
                    {
                        "name": "cve_search",
                        "method": "GET",
                        "path": "/v1/cves",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Search CVEs by product, severity, date",
                        "params": {"product": "str", "severity": "str", "days": "int", "limit": "int"},
                        "response_keys": ["count", "summary", "results"],
                    },
                    {
                        "name": "cve_leading",
                        "method": "GET",
                        "path": "/v1/cve/leading",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "CVEs indexed from MITRE/GHSA before NVD — early-warning feed",
                        "params": {"limit": "int", "offset": "int"},
                        "response_keys": ["count", "total", "summary", "results"],
                    },
                    {
                        "name": "exploit_lookup",
                        "method": "GET",
                        "path": "/v1/exploit/{cve_id}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "Public exploits from GitHub Advisory and ExploitDB",
                        "response_keys": ["cve_id", "exploits_found", "sources", "has_public_exploit", "summary"],
                    },
                    {
                        "name": "calculate_risk_score",
                        "method": "GET",
                        "path": "/v1/cve/{cve_id}/risk_score",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Composite CVE risk score (0-100): CVSS+EPSS+KEV+PoC fusion with multiplicative boosters",
                        "response_keys": [
                            "cve_id",
                            "score",
                            "label",
                            "urgency",
                            "has_public_poc",
                            "components",
                            "boosters_applied",
                            "recommendation",
                            "summary",
                        ],
                    },
                    {
                        "name": "get_cvss_details",
                        "method": "GET",
                        "path": "/v1/cvss/details",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Parse a CVSS v3.x vector string into per-metric breakdown + recomputed base score",
                        "params": {"vector": "str (CVSS:3.x vector)"},
                        "response_keys": [
                            "version",
                            "vector",
                            "base_score",
                            "base_severity",
                            "metrics",
                            "temporal_score",
                            "environmental_score",
                            "summary",
                        ],
                    },
                    {
                        "name": "bulk_cve_lookup",
                        "method": "POST",
                        "path": "/v1/cves/bulk",
                        "credit_cost": 1,
                        "credit_cost_note": "1 credit per item in request",
                        "blast_radius": "zero",
                        "description": "Bulk CVE lookup",
                        "body": {"cve_ids": "list[str] (max 50; same cap Free and Pro)"},
                        "response_keys": ["results", "total", "successful", "failed", "summary"],
                    },
                    {
                        "name": "kev_detail",
                        "method": "GET",
                        "path": "/v1/kev/{cve_id}",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "CISA KEV detail: federal patch deadline, required action, ransomware association, CWE list",
                        "response_keys": [
                            "cve_id",
                            "vendor_project",
                            "product",
                            "vulnerability_name",
                            "due_date",
                            "required_action",
                            "known_ransomware_use",
                            "cwes",
                            "next_calls",
                        ],
                    },
                    {
                        "name": "cwe_lookup",
                        "method": "GET",
                        "path": "/v1/cwe/{cwe_id}",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "MITRE CWE catalog (research view 1000): description, mitigations, parent/child weakness chain, CVE count",
                        "response_keys": [
                            "cwe_id",
                            "name",
                            "description",
                            "abstract_type",
                            "mitigations",
                            "parent_cwe",
                            "child_cwes",
                            "cve_count",
                            "next_calls",
                        ],
                    },
                ],
            },
            "domain": {
                "description": "Domain intelligence: DNS, WHOIS, SSL, subdomains, WAF, email security, threat intel, risk scoring",
                "tools": [
                    {
                        "name": "domain_report",
                        "method": "GET",
                        "path": "/v1/domain/{domain}",
                        "credit_cost": 1,
                        "blast_radius": "high",
                        "description": "Full domain report: DNS, WHOIS, SSL, subdomains, WAF, email security, threat intel, risk score",
                        "params": {"lite": "bool (fast subset ~250ms)"},
                        "response_keys": [
                            "domain",
                            "summary",
                            "dns",
                            "whois",
                            "ssl",
                            "email_security",
                            "subdomains",
                            "waf",
                            "threat",
                            "risk",
                        ],
                    },
                    {
                        "name": "audit_domain",
                        "method": "GET",
                        "path": "/v1/audit/{domain}",
                        "credit_cost": COST_AUDIT,
                        "blast_radius": "high",
                        "description": "Orchestrated domain audit: full report + tech fingerprint + live HTTP headers in one call",
                        "response_keys": ["domain", "report", "technologies", "live_headers", "summary"],
                    },
                    {
                        "name": "contrast_scan",
                        "method": "GET",
                        "path": "/v1/scan/{domain}",
                        "credit_cost": COST_SCAN,
                        "blast_radius": "high",
                        "description": "Active website security scan: C engine (11 modules — headers/SSL/DNS/CSP/cookies/CORS/DNSSEC/methods/redirect/disclosure/HTML) + severity-ranked findings + letter grade",
                        "response_keys": ["domain", "resolved_ip", "grade", "findings", "findings_count", "summary"],
                    },
                    {
                        "name": "threat_report",
                        "method": "GET",
                        "path": "/v1/threat-report/{ip}",
                        "credit_cost": COST_THREAT_REPORT,
                        "blast_radius": "low",
                        "description": "Orchestrated IP threat report: Shodan + AbuseIPDB + ASN. No private IPs.",
                        "response_keys": ["ip", "enrichment", "abuseipdb", "shodan", "asn", "threat_level", "summary"],
                    },
                    {
                        "name": "dns_lookup",
                        "method": "GET",
                        "path": "/v1/dns/{domain}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "DNS records: A, AAAA, MX, NS, TXT, CNAME, SOA",
                        "response_keys": ["domain", "records", "summary"],
                    },
                    {
                        "name": "whois_lookup",
                        "method": "GET",
                        "path": "/v1/whois/{domain}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "WHOIS registration data",
                        "response_keys": ["domain", "whois", "summary"],
                    },
                    {
                        "name": "ssl_check",
                        "method": "GET",
                        "path": "/v1/ssl/{domain}",
                        "credit_cost": 1,
                        "blast_radius": "high",
                        "description": "SSL/TLS certificate analysis: cipher, chain, expiry, grade",
                        "response_keys": [
                            "domain",
                            "valid",
                            "issuer",
                            "grade",
                            "days_remaining",
                            "protocol",
                            "cipher",
                            "summary",
                        ],
                    },
                    {
                        "name": "subdomain_enum",
                        "method": "GET",
                        "path": "/v1/subdomains/{domain}",
                        "credit_cost": 1,
                        "blast_radius": "high",
                        "description": "Subdomain enumeration via DNS brute force and CT logs",
                        "response_keys": ["domain", "subdomains", "count", "summary"],
                    },
                    {
                        "name": None,
                        "method": "GET",
                        "path": "/v1/certs/{domain}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "Certificate Transparency log entries",
                        "response_keys": ["domain", "total_certificates", "certificates", "summary"],
                    },
                    {
                        "name": "ip_lookup",
                        "method": "GET",
                        "path": "/v1/ip/{ip}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "IP intelligence via Shodan InternetDB. No private/reserved IPs.",
                        "response_keys": ["ip", "ptr", "ports", "hostnames", "vulns", "cpes", "tags", "summary"],
                    },
                    {
                        "name": "asn_lookup",
                        "method": "GET",
                        "path": "/v1/asn/{target}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "ASN lookup. Accepts domain or IP.",
                        "response_keys": [
                            "target",
                            "resolved_ip",
                            "asn",
                            "asn_name",
                            "ipv4_prefixes",
                            "ipv6_prefixes",
                            "summary",
                        ],
                    },
                    {
                        "name": "threat_intel",
                        "method": "GET",
                        "path": "/v1/threat/{domain}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "Threat intelligence via URLhaus malware URL lookup",
                        "response_keys": [
                            "domain",
                            "urlhaus_status",
                            "urls_online",
                            "url_count",
                            "threat_types",
                            "summary",
                        ],
                    },
                    {
                        "name": "tech_fingerprint",
                        "method": "GET",
                        "path": "/v1/tech/{domain}",
                        "credit_cost": 1,
                        "blast_radius": "high",
                        "description": "Technology fingerprinting: CMS, frameworks, servers, CDN, analytics",
                        "response_keys": ["domain", "technologies", "categories", "count", "summary"],
                    },
                    {
                        "name": "tech_stack_cve_audit",
                        "method": None,
                        "path": None,
                        "credit_cost": COST_TECH_CVE_AUDIT,
                        "blast_radius": "high",
                        "description": "MCP-only composite: tech fingerprint + bulk CVE lookup + KEV + exploit findings",
                        "response_keys": [
                            "domain",
                            "technologies",
                            "cves_by_tech",
                            "kev_findings",
                            "exploit_findings",
                            "summary",
                        ],
                    },
                    {
                        "name": "scan_headers",
                        "method": "GET",
                        "path": "/v1/scan/headers/{domain}",
                        "credit_cost": 1,
                        "blast_radius": "high",
                        "description": "Live HTTP security header scan and analysis",
                        "response_keys": [
                            "domain",
                            "status_code",
                            "score",
                            "grade",
                            "findings",
                            "headers_present",
                            "headers_missing",
                            "summary",
                        ],
                    },
                    {
                        "name": "email_mx",
                        "method": "GET",
                        "path": "/v1/email/mx/{domain}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "Email MX analysis: provider, SPF/DMARC/DKIM, security grade",
                        "response_keys": ["domain", "mx_records", "mail_provider", "email_security", "summary"],
                    },
                    {
                        "name": "email_security_posture",
                        "method": "GET",
                        "path": "/v1/email/security-posture/{domain}",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "SPF/DMARC/DKIM posture audit with score 0-100, grade A+-F, and discrete findings",
                        "response_keys": [
                            "domain",
                            "spf",
                            "dmarc",
                            "dkim",
                            "posture_score",
                            "posture_grade",
                            "all_findings",
                            "summary",
                        ],
                    },
                    {
                        "name": "email_disposable",
                        "method": "GET",
                        "path": "/v1/email/disposable/{email}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "Check if email uses a disposable/temporary provider",
                        "response_keys": ["email", "domain", "disposable", "provider", "risk_level", "summary"],
                    },
                    {
                        "name": "email_verify",
                        "method": "GET",
                        "path": "/v1/email/verify/{email}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "Combined email validation: syntax + MX + disposable + role + free-provider (NO SMTP probe)",
                        "response_keys": [
                            "email",
                            "domain",
                            "syntax_valid",
                            "mx_records",
                            "disposable",
                            "disposable_provider",
                            "role_address",
                            "role_type",
                            "free_provider",
                            "summary",
                        ],
                    },
                    {
                        "name": "robots_txt",
                        "method": "GET",
                        "path": "/v1/robots/{domain}",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Fetch + parse target domain's robots.txt (sitemaps, per-UA rules, crawl-delay)",
                        "response_keys": [
                            "domain",
                            "fetched_url",
                            "status_code",
                            "sitemaps",
                            "user_agents",
                            "host",
                            "truncated",
                            "summary",
                        ],
                    },
                    {
                        "name": "redirect_chain",
                        "method": "GET",
                        "path": "/v1/redirect/{url:path}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "Walk a URL's HTTP redirect chain hop-by-hop (deobfuscate URL shorteners, trace tracking redirects)",
                        "response_keys": [
                            "start_url",
                            "final_url",
                            "hops",
                            "hop_count",
                            "final_status",
                            "loop_detected",
                            "truncated",
                            "summary",
                        ],
                    },
                    {
                        "name": "brand_assets",
                        "method": "GET",
                        "path": "/v1/brand/{domain}",
                        "credit_cost": 2,
                        "blast_radius": "low",
                        "description": "Scrape a domain's homepage <head> for public brand assets (favicon, og:image, theme-color, og:site_name, JSON-LD logo). Honours robots.txt — Disallow: / returns 403 robots_txt_disallow.",
                        "response_keys": [
                            "domain",
                            "fetched_url",
                            "status_code",
                            "favicon_url_untrusted",
                            "og_image_url_untrusted",
                            "theme_color",
                            "site_name_untrusted",
                            "logo_url_untrusted",
                            "cache_respected",
                            "summary",
                        ],
                    },
                    {
                        "name": "seo_audit",
                        "method": "GET",
                        "path": "/v1/seo/{domain}",
                        "credit_cost": 2,
                        "blast_radius": "low",
                        "description": "One-page SEO audit of a domain's homepage with a 0-100 composite score (10 rules: title, meta description, H1, canonical, OG tags, JSON-LD, alt coverage, HTTPS). Honours robots.txt.",
                        "response_keys": [
                            "domain",
                            "fetched_url",
                            "status_code",
                            "title_untrusted",
                            "meta_description_untrusted",
                            "canonical_url",
                            "h1_untrusted",
                            "h1_count",
                            "h2_count",
                            "h3_count",
                            "images_total",
                            "images_missing_alt",
                            "internal_link_count",
                            "external_link_count",
                            "og_tags",
                            "json_ld_present",
                            "score",
                            "missing_signals",
                            "cache_respected",
                            "summary",
                        ],
                    },
                    {
                        "name": "phone_lookup",
                        "method": "GET",
                        "path": "/v1/phone/{number}",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Phone number validation and OSINT. Include country code e.g. +14155551234.",
                        "response_keys": [
                            "valid",
                            "number",
                            "format",
                            "country_code",
                            "country_name",
                            "type",
                            "carrier",
                            "timezone",
                            "summary",
                        ],
                    },
                    {
                        "name": "username_lookup",
                        "method": "GET",
                        "path": "/v1/username/{username}",
                        "credit_cost": 1,
                        "blast_radius": "high",
                        "description": "Username OSINT across 16 platforms (3-39 chars). Retries on rate-limit/block; check verdict.sources_unavailable for platforms that couldn't be reached.",
                        "response_keys": ["username", "found_count", "checked_count", "results", "summary", "verdict"],
                    },
                    {
                        "name": "wayback_lookup",
                        "method": "GET",
                        "path": "/v1/archive/{domain}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "Wayback Machine historical snapshots",
                        "response_keys": [
                            "domain",
                            "total_snapshots",
                            "first_seen",
                            "last_seen",
                            "years_online",
                            "snapshots",
                            "archive_url",
                            "summary",
                        ],
                    },
                ],
            },
            "ioc": {
                "description": "IOC enrichment, hash reputation, password breach, phishing detection",
                "tools": [
                    {
                        "name": "ioc_lookup",
                        "method": "GET",
                        "path": "/v1/ioc/{indicator}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "Unified IOC enrichment. Auto-detects IP/domain/URL/hash. Sources: ThreatFox, URLhaus, Feodo.",
                        "response_keys": ["indicator", "type", "threat_level", "sources", "summary"],
                    },
                    {
                        "name": "hash_lookup",
                        "method": "GET",
                        "path": "/v1/hash/{file_hash}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "Malware hash reputation via MalwareBazaar. MD5/SHA1/SHA256.",
                        "response_keys": [
                            "hash",
                            "hash_type",
                            "found",
                            "malware_family",
                            "file_type",
                            "tags",
                            "summary",
                        ],
                    },
                    {
                        "name": "password_check",
                        "method": "GET",
                        "path": "/v1/password/{sha1_hash}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "Password breach check via HIBP k-anonymity. Pass full SHA1 hash.",
                        "response_keys": ["hash_prefix", "found", "breach_count", "summary"],
                    },
                    {
                        "name": "phishing_check",
                        "method": "GET",
                        "path": "/v1/phishing/{url}",
                        "credit_cost": 1,
                        "blast_radius": "low",
                        "description": "Phishing/malware URL check via URLhaus. URL must start with http(s)://.",
                        "response_keys": ["url", "host", "is_malicious", "threat_level", "summary"],
                    },
                    {
                        "name": "bulk_ioc_lookup",
                        "method": "POST",
                        "path": "/v1/iocs/bulk",
                        "credit_cost": 1,
                        "credit_cost_note": "1 credit per item in request",
                        "blast_radius": "low",
                        "description": "Bulk IOC enrichment",
                        "body": {"indicators": "list[str] (max 50; same cap Free and Pro)"},
                        "response_keys": ["results", "total", "successful", "failed", "summary"],
                    },
                ],
            },
            "code_security": {
                "description": "Static code analysis: secrets detection, injection detection, header validation, dependency CVE check",
                "tools": [
                    {
                        "name": "check_secrets",
                        "method": "POST",
                        "path": "/v1/check/secrets",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Detect hardcoded secrets (14 patterns: API keys, tokens, passwords)",
                        "body": {"code": "str", "language": "str"},
                        "response_keys": ["findings", "total", "by_severity", "summary"],
                    },
                    {
                        "name": "check_injection",
                        "method": "POST",
                        "path": "/v1/check/injection",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "SQL, command, and path injection detection",
                        "body": {"code": "str", "language": "str"},
                        "response_keys": ["findings", "total", "by_severity", "summary"],
                    },
                    {
                        "name": "check_headers",
                        "method": "POST",
                        "path": "/v1/check/headers",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Validate HTTP security headers",
                        "body": {"headers": "dict[str, str]"},
                        "response_keys": [
                            "findings",
                            "total",
                            "by_severity",
                            "score",
                            "grade",
                            "headers_present",
                            "headers_missing",
                            "summary",
                        ],
                    },
                    {
                        "name": "check_dependencies",
                        "method": "POST",
                        "path": "/v1/check/dependencies",
                        "credit_cost": 1,
                        "credit_cost_note": "1 credit per package in request",
                        "blast_radius": "zero",
                        "description": "Check packages against CVE database",
                        "body": {"packages": "list[{name: str, version: str}] (max 50; same cap Free and Pro)"},
                        "response_keys": ["findings", "total", "by_severity", "summary"],
                    },
                ],
            },
            "d3fend": {
                "description": "MITRE D3FEND — defense technique catalog mapped to ATT&CK (149 defenses, ~3k mappings)",
                "tools": [
                    {
                        "name": "d3fend_defense_lookup",
                        "method": "GET",
                        "path": "/v1/d3fend/{defense_id}",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Lookup D3FEND defense by slug (e.g. TokenBinding) — returns tactic, artifact, mapped ATT&CK T-codes",
                        "response_keys": [
                            "defense_id",
                            "label",
                            "uri",
                            "parent_label",
                            "tactic",
                            "artifact",
                            "attack_techniques",
                            "next_calls",
                        ],
                    },
                    {
                        "name": "d3fend_defense_search",
                        "method": "GET",
                        "path": "/v1/d3fend/defenses",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Search D3FEND defenses by keyword, tactic, or targeted artifact",
                        "response_keys": ["query", "total", "results", "next_calls"],
                    },
                    {
                        "name": "d3fend_defense_for_attack",
                        "method": "GET",
                        "path": "/v1/d3fend/attack/{attack_technique_id}",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Reverse lookup: given an ATT&CK T-code, return all D3FEND defenses that mitigate it",
                        "response_keys": [
                            "attack_technique_id",
                            "total",
                            "defenses",
                            "coverage_by_tactic",
                            "next_calls",
                        ],
                    },
                    {
                        "name": "d3fend_attack_coverage",
                        "method": "POST",
                        "path": "/v1/d3fend/coverage",
                        "credit_cost": 1,
                        "credit_cost_note": "1 credit per request (not per T-code)",
                        "blast_radius": "zero",
                        "description": "Batch coverage breakdown: count defenses per tactic + identify undefended ATT&CK techniques",
                        "body": {"attack_technique_ids": "list[str] (max 500)"},
                        "response_keys": [
                            "queried_techniques",
                            "coverage_by_tactic",
                            "defended_techniques",
                            "undefended_techniques",
                            "next_calls",
                        ],
                    },
                ],
            },
            "sigma": {
                "description": "SigmaHQ detection rule corpus (~3,200 rules, daily sync) — UUID lookup + bulk lookup for blue-team triage",
                "tools": [
                    {
                        "name": "sigma_rule_lookup",
                        "method": "GET",
                        "path": "/v1/sigma/{rule_id}",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Lookup a single Sigma rule by UUID — full rule with title, level, logsource, detection logic, tags (attack.t#### / cve.YYYY-####), references",
                        "response_keys": ["rule", "next_calls"],
                    },
                    {
                        "name": "bulk_sigma_rule_lookup",
                        "method": "POST",
                        "path": "/v1/sigma/bulk",
                        "credit_cost": 1,
                        "credit_cost_note": "1 credit per rule_id (each id counts)",
                        "blast_radius": "zero",
                        "description": "Bulk lookup up to 50 Sigma rule UUIDs in one request — per-item status (ok/not_found/invalid_format)",
                        "body": {"rule_ids": "list[str] (max 50)"},
                        "response_keys": [
                            "results",
                            "total",
                            "successful",
                            "failed",
                            "partial",
                            "summary",
                            "next_calls",
                        ],
                    },
                ],
            },
            "atlas": {
                "description": "MITRE ATLAS — AI/ML adversarial attack catalog (techniques + case studies)",
                "tools": [
                    {
                        "name": "atlas_technique_lookup",
                        "method": "GET",
                        "path": "/v1/atlas/{technique_id}",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Lookup ATLAS technique by id (AML.T#### or AML.T####.###)",
                        "response_keys": [
                            "technique_id",
                            "name",
                            "description",
                            "tactics",
                            "maturity",
                            "attack_reference_id",
                            "next_calls",
                        ],
                    },
                    {
                        "name": "atlas_technique_search",
                        "method": "GET",
                        "path": "/v1/atlas/techniques",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Search ATLAS technique catalog by keyword, tactic, or maturity",
                        "response_keys": ["query", "total", "results", "next_calls"],
                    },
                    {
                        "name": "bulk_atlas_technique_lookup",
                        "method": "POST",
                        "path": "/v1/atlas/techniques/bulk",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Bulk lookup up to 50 ATLAS technique ids in one request (drill case study techniques_used in one call)",
                        "response_keys": [
                            "results",
                            "total",
                            "successful",
                            "failed",
                            "partial",
                            "summary",
                        ],
                    },
                    {
                        "name": "atlas_case_study_lookup",
                        "method": "GET",
                        "path": "/v1/atlas/case-studies/{case_study_id}",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Lookup ATLAS case study (real-world AI/ML incident) by id",
                        "response_keys": [
                            "case_study_id",
                            "name",
                            "description",
                            "techniques_used",
                            "next_calls",
                        ],
                    },
                    {
                        "name": "atlas_case_study_search",
                        "method": "GET",
                        "path": "/v1/atlas/case-studies",
                        "credit_cost": 1,
                        "blast_radius": "zero",
                        "description": "Search ATLAS case studies by keyword or referenced technique",
                        "response_keys": ["query", "total", "results", "next_calls"],
                    },
                ],
            },
            "meta": {
                "description": "API status, usage statistics, capabilities",
                "tools": [
                    {
                        "name": None,
                        "method": "GET",
                        "path": "/v1/status",
                        "credit_cost": 0,
                        "description": "API health check and data freshness",
                    },
                    {
                        "name": None,
                        "method": "GET",
                        "path": "/v1/usage",
                        "credit_cost": 0,
                        "description": "Usage statistics for authenticated API key holders",
                        "auth_required": True,
                    },
                    {
                        "name": None,
                        "method": "GET",
                        "path": "/v1/capabilities",
                        "credit_cost": 0,
                        "description": "This endpoint — machine-readable tool catalog",
                    },
                ],
            },
        },
    }
