name: Sync to Gitee

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Gitee
        uses: Yikun/hub-mirror-action@v1.4
        with:
          src: github/UPinar
          dst: gitee/UPinar
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "contrastapi"
          force_update: true
          timeout: 600
